<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="INLEN8520068267"><DocLocation><![CDATA[C:\UFT Framework\QTP-Hybrid-Framework\TestCases\OrangeHRM_framework]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[OrangeHRM_framework]]></DName>
<Res><![CDATA[Res47]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[15-02-2023 - 05:42:58]]></Time>
<TimeTick>1676419978</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63eb984214495f7dae03e1e0a08164ab5dee11ed7412"]]></Details>
<Time><![CDATA[15-02-2023 - 05:42:58]]></Time>
<TimeTick>1676419978</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" >
<Disp><![CDATA[[ password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[  Login  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 05:42:58]]></Time>
<TimeTick>1676419978</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" >
<Disp><![CDATA[[  Login  ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-02-2023 - 05:42:52" eTime="15-02-2023 - 05:42:58" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T8">
<AName><![CDATA[Search]]></AName>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ PIM ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:00]]></Time>
<TimeTick>1676419980</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" >
<Disp><![CDATA[[ PIM ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0007"]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:02]]></Time>
<TimeTick>1676419982</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="36" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[  Search  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:02]]></Time>
<TimeTick>1676419982</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" >
<Disp><![CDATA[[  Search  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[  Reset  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:02]]></Time>
<TimeTick>1676419982</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" >
<Disp><![CDATA[[  Reset  ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-02-2023 - 05:42:58" eTime="15-02-2023 - 05:43:02" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="30" >
<Disp><![CDATA[Search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[Add]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[  Add  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:03]]></Time>
<TimeTick>1676419983</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" >
<Disp><![CDATA[[  Add  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ firstName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["John"]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:04]]></Time>
<TimeTick>1676419984</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="50" >
<Disp><![CDATA[[ firstName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ lastName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Smith"]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:04]]></Time>
<TimeTick>1676419984</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="53" >
<Disp><![CDATA[[ lastName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[  Save  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:05]]></Time>
<TimeTick>1676419985</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" >
<Disp><![CDATA[[  Save  ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-02-2023 - 05:43:02" eTime="15-02-2023 - 05:43:05" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="44" >
<Disp><![CDATA[Add Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T18">
<AName><![CDATA[MyInfo]]></AName>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ My Info ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:05]]></Time>
<TimeTick>1676419985</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="63" >
<Disp><![CDATA[[ My Info ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ firstName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rio"]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:07]]></Time>
<TimeTick>1676419987</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="66" >
<Disp><![CDATA[[ firstName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ lastName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Walt"]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:07]]></Time>
<TimeTick>1676419987</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="69" >
<Disp><![CDATA[[ lastName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ yyyy-mm-dd ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["08-1975-10"]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:08]]></Time>
<TimeTick>1676419988</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="74" >
<Disp><![CDATA[[ yyyy-mm-dd ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[  Save  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:08]]></Time>
<TimeTick>1676419988</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="77" >
<Disp><![CDATA[[  Save  ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-02-2023 - 05:43:05" eTime="15-02-2023 - 05:43:08" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="60" >
<Disp><![CDATA[MyInfo Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T24">
<AName><![CDATA[Logout]]></AName>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;name:OrangeHRM&quot;  object was not found in the Object Repository.<BR/>Check the Object Repository to confirm that the object exists or to find the correct name for the object.<BR/>Function file: C:\UFT Framework\QTP-Hybrid-Framework\Resources\GenericFL\Orange_AppSpecificfl.qfl<BR/>Line (44): &quot;	Browser(&quot;name:OrangeHRM&quot;).Page(&quot;title:=OrangeHRM&quot;).WebElement(&quot;xpath:=//*[@id='app']/div[1]/div[1]/header/div[1]/div[2]/ul/li/span&quot;).Click&quot;.]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:08]]></Time>
<TimeTick>1676419988</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" status="Failed" Source="C:\UFT Framework\QTP-Hybrid-Framework\Resources\GenericFL\Orange_AppSpecificfl.qfl" SourceLine="43" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[15-02-2023 - 05:43:27]]></Time>
<TimeTick>1676420007</TimeTick>
<NodeArgs eType="General" icon="9" nRep="81" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-02-2023 - 05:43:08" eTime="15-02-2023 - 05:43:27" passed="0" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="79" status="Failed" >
<Disp><![CDATA[Logout Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[OrangeHRM_framework Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="15-02-2023 - 05:42:49" eTime="15-02-2023 - 05:43:27" passed="0" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test OrangeHRM_framework Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>